name:  Publish docs on GitHub Pages

on:
  push:
    branches:
      - ci_dev

jobs:
  build:
    name: Deploy docs
    runs-on: self-hosted
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Publish last version
        run: |
          set -e
          if ! git config --get user.name; then
              git config --global user.name "${GITHUB_ACTOR}"
          fi
          if ! git config --get user.email; then
              git config --global user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"
          fi
          remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
          git remote rm origin
          git remote add origin "${remote_repo}"
          git checkout --orphan gh-pages
          git pull origin gh-pages
          git checkout master
          mkdocs gh-deploy
